version: "3.8"

services:
  app:
    container_name: ynoverflow_back
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      PORT: ${PORT}
    ports:
      - "10000:${PORT}"
    volumes:
      - ./:/app
  db:
    image: postgres:12.2-alpine
    container_name: ynoverflow_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ynoverflow-vol:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "10001:5432"

volumes:
  ynoverflow-vol: